[package]
name = "rust-phil-os"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9.8"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
spin = "0.10.0"
